In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
resturant_df = pd.read_csv('dataset/restaurants.csv')
resturant_df

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752304,-99.166913,NaN,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.730925,-99.145185,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,NaN,18.876011,-99.219890,NaN,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,78000.0,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,NaN
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.136253,-100.933585,NaN,No,Low,No,Closed,NaN
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,NaN,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,NaN

In [4]:
resturant_df.shape

(130, 14)

In [5]:
resturant_df.describe()

       Restaurant_ID      Zip_Code    Latitude   Longitude
count     130.000000     56.000000  130.000000  130.000000
mean   134012.784615  75790.714286   21.858863 -100.342933
std      1140.644582   6018.162410    1.496830    0.860585
min    132560.000000  62000.000000   18.859803 -101.028600
25%    132831.000000  78000.000000   22.139574 -100.987838
50%    134994.000000  78212.000000   22.149063 -100.956777
75%    135050.750000  78310.000000   22.160125  -99.220458
max    135109.000000  87018.000000   23.760268  -99.126506

In [10]:
resturant_df.isna().sum()

Restaurant_ID       0
Name                0
City                0
State               0
Country             0
Zip_Code           74
Latitude            0
Longitude           0
Alcohol_Service    87
Smoking_Allowed     0
Price               0
Franchise           0
Area                0
Parking            65
dtype: int64

In [30]:
resturant_df['Parking'] = resturant_df['Parking'].replace(np.nan, 'No')

In [31]:
resturant_df.isna().sum()

Restaurant_ID       0
Name                0
City                0
State               0
Country             0
Zip_Code           74
Latitude            0
Longitude           0
Alcohol_Service    87
Smoking_Allowed     0
Price               0
Franchise           0
Area                0
Parking             0
dtype: int64

In [32]:
resturant_df['Parking']

0      Public
1          No
2          No
3         Yes
4          No
        ...
125    Public
126       Yes
127        No
128        No
129        No
Name: Parking, Length: 130, dtype: object

In [40]:
resturant_df['Alcohol_Service']

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
          ...
125            NaN
126       Full Bar
127    Wine & Beer
128            NaN
129    Wine & Beer
Name: Alcohol_Service, Length: 130, dtype: object

In [41]:
resturant_df['Alcohol_Service'].describe()

count              43
unique              2
top       Wine & Beer
freq               34
Name: Alcohol_Service, dtype: object

In [42]:
resturant_df['Alcohol_Service'].unique()

array([nan, 'Full Bar', 'Wine & Beer'], dtype=object)

In [43]:
resturant_df['Alcohol_Service'] = resturant_df['Alcohol_Service'].replace(np.nan, 'No Service')

In [44]:
resturant_df.isna().sum()

Restaurant_ID       0
Name                0
City                0
State               0
Country             0
Zip_Code           74
Latitude            0
Longitude           0
Alcohol_Service     0
Smoking_Allowed     0
Price               0
Franchise           0
Area                0
Parking             0
dtype: int64

In [48]:

resturant_df = resturant_df.drop('Zip_Code', axis=1)

In [49]:
resturant_df

,Restaurant_ID,Name,City,State,Country,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,23.752304,-99.166913,No Service,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,23.726819,-99.126506,No Service,No,Low,No,Closed,No
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,23.730925,-99.145185,No Service,No,Low,No,Closed,No
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,22.141647,-100.992712,No Service,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,18.922290,-99.234332,No Service,No,Low,Yes,Closed,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,18.876011,-99.219890,No Service,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,No
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,22.136253,-100.933585,No Service,No,Low,No,Closed,No
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,No

In [51]:
resturant_df.isna().sum()

Restaurant_ID      0
Name               0
City               0
State              0
Country            0
Latitude           0
Longitude          0
Alcohol_Service    0
Smoking_Allowed    0
Price              0
Franchise          0
Area               0
Parking            0
dtype: int64

In [53]:
resturant_df.to_csv('cleaned_resturant.csv', index=False)